/*
 * This source file was generated by the Gradle 'init' task
 */
package scari.corp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FileFilterUtilTest {
    @Test void appHasAGreeting() {
        FileFilterUtil classUnderTest = new FileFilterUtil();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
