/*
 * This source file was generated by the Gradle 'init' task
 */
package scari.corp;

import org.apache.commons.cli.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import scari.corp.config.CliConfig;
import scari.corp.core.FileProcessor;
import scari.corp.model.Stats;

import java.util.Arrays;

public class FileFilterUtil {

    private static final Logger log = LoggerFactory.getLogger(FileFilterUtil.class);

    public static void main(String[] args) {

        Options options = new Options();
        options.addOption("o", "output", true, "Каталог выходного файла");
        options.addOption("p", "prefix", true, "Префикс имени выходного файла");
        options.addOption("s", "short-stats", false, "Вывод краткой статистики");
        options.addOption("f", "full-stats", false, "Вывод полной статистики");
        options.addOption("a", "append", false, "Добавить в существующий файл");

        CommandLineParser parser = new DefaultParser();
        CommandLine cmd;

        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            log.error("Ошибка разбора аргументов: {}", e.getMessage());
            new HelpFormatter().printHelp("java -jar file.jar [options] files...", options);
            return;
        }

        CliConfig cliConfig;
        try {
            cliConfig = buildCliConfig(cmd);
        } catch (IllegalArgumentException e) {
            log.error("Ошибка параметров: {}", e.getMessage());
            new HelpFormatter().printHelp("java -jar file.jar [options] files...", options);
            return;
        }


        if (cliConfig.inputFiles().length == 0) {
            log.error("Не указаны входные файлы");
            new HelpFormatter().printHelp("java -jar file.jar [options] files...", options);
            return;
        }

        FileProcessor processor = new FileProcessor();

        FileProcessor.OutputFiles out = processor.buildOutputFiles(cliConfig.outputDir(), cliConfig.prefix());

        Stats stats = processor.processFiles(cliConfig.inputFiles(), out, cliConfig.append());

        printConfig(cliConfig);

        printStats(stats, cliConfig.shortStats());

    }

    private static CliConfig buildCliConfig(CommandLine cmd) {
        String outputDir = cmd.getOptionValue("o", ".");
        String prefix = cmd.getOptionValue("p", "");
        boolean shortStats = cmd.hasOption("s");
        boolean fullStats = cmd.hasOption("f");
        boolean append = cmd.hasOption("a");
        String[] inputFiles = cmd.getArgs();

        if (shortStats && fullStats) {
            throw new IllegalArgumentException("Одновременно использовать -s и -f запрещено");
        }

        return new CliConfig(outputDir, prefix, shortStats, append, inputFiles);
    }

    private static void printConfig(CliConfig config) {
        log.info("Опции: outputDir={}, prefix={}, shortStats={}, append={}, файлы={}",
                config.outputDir(), config.prefix(), config.shortStats(), config.append(),
                Arrays.toString(config.inputFiles()));

    }

    private static void printStats(Stats stats, boolean shortStats) {
        log.info("Статистика — shortStats= {}", shortStats);
        log.info(" integers: {}, floats: {}, strings: {}", stats.intCount, stats.floatCount, stats.stringCount);

        if (shortStats) {
            return;
        }

        if (stats.intCount > 0) {
            double avg = (double) stats.intSum / stats.intCount;
            log.info("Integer stats: count={}, min={}, max={}, sum={}, avg={}",
                    stats.intCount, stats.intMin, stats.intMax, stats.intSum, avg);
        }

        if (stats.floatCount > 0) {
            double avg = stats.floatSum / stats.floatCount;
            log.info("Float  stats: count={}, min={}, max={}, sum={}, avg={}",
                    stats.floatCount, stats.floatMin, stats.floatMax, stats.floatSum, avg);
        }

        if (stats.stringCount > 0) {
            log.info("String stats: count={}, minLen={}, maxLen={}",
                    stats.stringCount, stats.minStringLength, stats.maxStringLength);
        }
    }

}
